### Using Alpine
FROM alpine
RUN apk add php82 php82-pdo_mysql curl vim bash --update
ENTRYPOINT ["/bin/bash"]

### USING Ubuntu
# FROM ubuntu

# RUN apt-get update
# # RUN apk add mysql-client curl vim bash --update
# RUN apt-get install mysql-client vim curl -y
# RUN apt-get -y install php php-cli php-fpm php-json php-common php-mysql php-zip php-gd php-mbstring php-curl php-xml php-pear php-bcmath

# ENTRYPOINT ["/bin/bash"]
